---
# Ansible variables
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/ansible_key
become: yes

# LINSTOR variables
drbd_backing_disk: /dev/sdb
drbd_replication_network: 172.16.7.0/24

# LINBIT portal variables
lb_user: ""
lb_pass: ""
lb_con_id: ""
lb_clu_id: ""
